config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  post 'checkout', to: 'carts#checkout'

  resources :users, only:[:new, :create, :edit, :update]
  resources :books, only:[:index, :new, :create, :edit, :update, :destroy]
  resources :buy, only:[:new]
  resources :carts, only:[:show, :destroy]
  resources :cart_books, only:[:create, :destroy]
  resources :sales, only:[:index]
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :cart_books, dependent: :delete_all
  has_many :carts, through: :cart_books
  has_many :sales, dependent: :delete_all
  has_many :users, through: :sales

  validates :title, uniqueness: true, presence: true, length: { in: 2..30 }
  validates :description, presence: true, length: { in: 5..200 }
  validates :author, presence: true, length: { in: 2..30 }
  validates :price, presence: true, length: { in: 1..8 }

  def self.search(search)
    Book.find_by(title: search) ? Book.where(title: search, available: true) : Book.all.where(available: true)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.search(params[:search])
  end

  def new
    user_must_be_seller(new_book_path)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path, notice: 'Book successfully created'
    else
      flash.now[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def edit
    @book = find_book
  end

  def update
    @book = find_book
    if @book.update(book_params)
      redirect_to root_path, notice: 'Book was successfully updated'
    else
      flash[:alert] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    @book = find_book
    if @book.destroy
      redirect_to root_path, notice: 'Book was successfully deleted.'
    else
      flash[:alert] = 'Something went wrong'
    end
  end

  private

  def find_book
    Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :author, :price, :user_id, :available)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
  <table>
    <thead>
      <tr>
        <th class="px-4">Title</th>
        <th class="px-4">Description</th>
        <th class="px-4">Author</th >
        <th class="px-4">Price</th> 
        <th class="px-4">Seller</th>
        <th colspan="3"> </th>
      </tr>
    </thead>

    <tbody>
      <% books.each do |book| %>
        <tr id=<%="#{book.id}"%>>
          <td class="px-4"><%= book.title %></td>
          <td class="px-4"><%= book.description %></td>
          <td class="px-4"><%= book.author %></td>
          <td class="px-4"><%= number_to_currency(book.price) %></td>
          <td class="px-4"><%= book.user.name %></td>
          <td class="px-4"> <%= link_to "Add to cart", cart_books_path(book_id: book.id), method: :post, remote: true, class: "addToCart" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/edit.html.erb
<div>
    <% @book.errors.full_messages.each do |msg| %>
    <div>
        <%= msg %>
    </div>
    <% end %>

  <h5>Update Book</h5>

  <%= form_for @book, url: {action: "update"} do |f| %>
    
    <div>
      <%= f.label :title %>
      <br />
      <%= f.text_field :title, placeholder: "title"%><br />
    </div>

    <div>
      <%= f.label :description %>
      <br />
      <%= f.text_area :description, placeholder: "description"%><br />
    </div>

    <div>
      <%= f.label :author %>
      <br />
      <%= f.text_field :author, placeholder: "author"%><br />
    </div>

    <div>
      <%= f.label :price %>
      <br />
      <%= f.number_field :price, step: 0.01, placeholder: "$ 0.00"%><br />
    </div><br />
      
    <%= f.submit "Update" %>

  <% end %>
</div>

app/views/books/index.html.erb
<div>
  <%=form_tag(books_path, method: :get) do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search"%>
    </p>
  <% end %>

  <div id="books-container">
    <%=render partial: 'books', locals: {books: @books}%>
  </div>


</div>

app/views/books/new.html.erb
<div>
    <% @book.errors.full_messages.each do |msg| %>
    <div>
        <%= msg %>
    </div>
    <% end %>

  <h5>New Book</h5>

  <%= form_for @book, url: {action: "create"} do |f| %>
    
    <div>
      <%= f.label :title %>
      <br />
      <%= f.text_field :title, placeholder: "title"%><br />
    </div>

    <div>
      <%= f.label :description %>
      <br />
      <%= f.text_area :description, placeholder: "description"%><br />
    </div>

    <div>
      <%= f.label :author %>
      <br />
      <%= f.text_field :author, placeholder: "author"%><br />
    </div>

    <div>
      <%= f.label :price %>
      <br />
      <%= f.number_field :price, step: 0.01, placeholder: "$ 0.00"%><br />
    </div><br />

    <%=f.hidden_field :available, value: true %>
    <%=f.hidden_field :user_id, value: current_user.id %>
      
    <%= f.submit "Create" %>

  <% end %>
</div>