config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  post 'checkout', to: 'carts#checkout'

  resources :users, only:[:new, :create, :edit, :update]
  resources :books, only:[:index, :new, :create, :edit, :update, :destroy]
  resources :buy, only:[:new]
  resources :carts, only:[:show, :destroy]
  resources :cart_books, only:[:create, :destroy]
  resources :sales, only:[:index]
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_books, dependent: :delete_all
  has_many :books, through: :cart_books

  def self.total(cart)
    acc = 0
    cart.cart_books.each do |cb|
      acc += cb.qty * cb.book.price
    end
    acc
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :update_availability_books, only: [:destroy]

  def show
    @cart = Cart.find(params[:id])
    @total = current_total
  end

  def checkout
    user = current_user
    cart = current_cart
    total = current_total
    return if total.zero?

    check = user.balance - total
    if check.positive?
      user.update(balance: check)
      cart.books.each { |book| Sale.create(book_id: book.id, user_id: book.user_id) }
      cart.destroy
      redirect_to root_path, notice: 'Thanks for your purchase'
    else
      redirect_to cart_path(cart)
      flash[:alert] = 'Insufficient funds'
    end
  end

  def destroy
    cart = Cart.find(params[:id])
    if cart.destroy
      render_index_real_time
      redirect_to root_path, notice: 'Cart was successfully deleted'
    else
      flash[:alert] = 'Something went wrong'
      redirect_to cart_path
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="px-5 d-flex flex-column align-content-center justify-content-center">
    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th>Unit price</th>
          <th>Quantity</th >
          <th>Total</th >
          <th colspan="3"> </th>
        </tr>
      </thead>

      <tbody>
        <%@cart.cart_books.each do |cart_book|%>
          <tr>
            <td><%=cart_book.book.title%></td>
            <td><%= number_to_currency(cart_book.book.price)%></td>
            <td><%=cart_book.qty%></td>
            <td><%=number_to_currency(cart_book.qty * cart_book.book.price)%></td>
            <td><%=link_to "Remove", cart_book_path(cart_book, book_id: cart_book.book.id), method: :delete, remote: true, class: "px-4 deleteFromCart"%></td>
          </tr>
        <% end %> 
      </tbody>
    </table>

    <div class="w-25">
      <div class="mt-5">
          <strong>Total: </strong><div id="total"><%=number_to_currency(@total)%></div>
      </div>

      <div class="mt-3">
          <strong>Available credit: </strong><%=number_to_currency(current_user.balance)%>
      </div>

      <div class="d-flex align-content-center justify-content-between mt-3">
        <%= link_to "Checkout", checkout_path(total: @total),method: :post, data: {confirm: "Are you sure?"} if @total > 0%>
        <%= link_to "Empty cart", cart_path(current_cart),method: :delete, data: {confirm: "Are you sure?"} if @total > 0%>
      </div>
    </div>
</div>