config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  post 'checkout', to: 'carts#checkout'

  resources :users, only:[:new, :create, :edit, :update]
  resources :books, only:[:index, :new, :create, :edit, :update, :destroy]
  resources :buy, only:[:new]
  resources :carts, only:[:show, :destroy]
  resources :cart_books, only:[:create, :destroy]
  resources :sales, only:[:index]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TelosBookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar main-navbar border border-secondary bg-white px-4">
      
      <div>
        <%if user_signed_in?%>
          <%= link_to 'log_out', logout_path%>
          |
          <%= link_to 'Sales', sales_path%>
        <%else%>
            <%= link_to 'log_in', login_path %>
            <span>|</span>
            <%= link_to 'sign_up', signup_path %>
        <%end%>
      </div>

      <div class="d-flex flex-column align-items-center">
        <h1>Books Store</h1>
        <p><%= "Welcome #{current_user.name}" if user_signed_in?%></p>
        <%=link_to 'HOME', root_path%>  
      </div>

      <div>
        <%= link_to 'Sell', new_book_path%>
        <%if user_signed_in?%>
          <span>|</span>
          <%= link_to 'Go to Cart', cart_path(current_cart.id)%>
        <%end%>
      </div>

    </nav>
    <div class="mt-4 text-center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="container">
        <%= yield %>
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>